{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.amistad012oss.gradle",
    "module": "git-repo-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ydzhid5tmjgq3lk57ybxav6sh4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27077,
          "sha512": "672e652087f01d302b44047e87129e6512564b8267ec04d208de8c189a98b171ae8dde260c79b90139b2fe9f4d956f868bda87831ea4038a3b48007446630f4d",
          "sha256": "f0cb25f871dccba32819937306ac91c963b890973e407af5c58435fb1c45436f",
          "sha1": "3cf4f3505b848c42c79716f17b9892afc55da7b4",
          "md5": "fe8c16b1843f37b425a10833454f6088"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27077,
          "sha512": "672e652087f01d302b44047e87129e6512564b8267ec04d208de8c189a98b171ae8dde260c79b90139b2fe9f4d956f868bda87831ea4038a3b48007446630f4d",
          "sha256": "f0cb25f871dccba32819937306ac91c963b890973e407af5c58435fb1c45436f",
          "sha1": "3cf4f3505b848c42c79716f17b9892afc55da7b4",
          "md5": "fe8c16b1843f37b425a10833454f6088"
        }
      ]
    }
  ]
}
