{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.amistad012oss.gradle",
    "module": "git-repo-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "do7c4ijqg5fqtd5n2csamtmlqu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27933,
          "sha512": "be8c801f4f9567d6c75cd9ca6f2e56c1ba74527052fa4f2648c41dc2f0fb5fb184cfa810b1762246a7349545f7ffca7c83117910af3c2b8d2d22e52f622d3386",
          "sha256": "782e50bdea0087d7e5881cba35b11477a698a9f2640ddb94dfac153a49e94583",
          "sha1": "42d9f03bb9b94f5aa900fd51d6279f256d33610b",
          "md5": "27c69a0335df082ac5f472b73213c54d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27933,
          "sha512": "be8c801f4f9567d6c75cd9ca6f2e56c1ba74527052fa4f2648c41dc2f0fb5fb184cfa810b1762246a7349545f7ffca7c83117910af3c2b8d2d22e52f622d3386",
          "sha256": "782e50bdea0087d7e5881cba35b11477a698a9f2640ddb94dfac153a49e94583",
          "sha1": "42d9f03bb9b94f5aa900fd51d6279f256d33610b",
          "md5": "27c69a0335df082ac5f472b73213c54d"
        }
      ]
    }
  ]
}
