{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.amistad012oss.gradle",
    "module": "git-repo-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "blw5wqapl5abhmv26hpokwt6v4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27077,
          "sha512": "c241c3ad815f642d97752b2d70e23f210c7301aabe018393ebdade4e9f2afdd101f96af1fbf7ed88b436f7a2973eb8729e6f8f32923528eef2ded2c619817fb2",
          "sha256": "ffcf57c86fb7cb9a0d08960087b5797dd31ebf3deee1767af6aebf439997ae4b",
          "sha1": "05e9988b0c7be69d31af94d2b88bba1f2cbb9bc4",
          "md5": "d16f50c169005185b93beed5c0290100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27077,
          "sha512": "c241c3ad815f642d97752b2d70e23f210c7301aabe018393ebdade4e9f2afdd101f96af1fbf7ed88b436f7a2973eb8729e6f8f32923528eef2ded2c619817fb2",
          "sha256": "ffcf57c86fb7cb9a0d08960087b5797dd31ebf3deee1767af6aebf439997ae4b",
          "sha1": "05e9988b0c7be69d31af94d2b88bba1f2cbb9bc4",
          "md5": "d16f50c169005185b93beed5c0290100"
        }
      ]
    }
  ]
}
