{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.amistad012oss",
    "module": "git-repo-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wx6dehskmbfflahtjfmoqz6fsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27424,
          "sha512": "1d9a7ac319309ecdcbf4aac5e3e5f430487e382eeaf9932b3a7087f7c10b2708d4a981b1f9e17a9d45a4a320a7f5cb1e301056af685915ad413b1354a4aa2bb0",
          "sha256": "15caa4439282a39fbdb92bdba21bac69fcb484ad949b5bd27c0257f49c238ed1",
          "sha1": "06b353f705e6edfa4436f4762e5780d6a11eedfb",
          "md5": "f832b527aa8aac14e5c9a70c578f75ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-1.0.0.jar",
          "url": "git-repo-plugin-1.0.0.jar",
          "size": 27424,
          "sha512": "1d9a7ac319309ecdcbf4aac5e3e5f430487e382eeaf9932b3a7087f7c10b2708d4a981b1f9e17a9d45a4a320a7f5cb1e301056af685915ad413b1354a4aa2bb0",
          "sha256": "15caa4439282a39fbdb92bdba21bac69fcb484ad949b5bd27c0257f49c238ed1",
          "sha1": "06b353f705e6edfa4436f4762e5780d6a11eedfb",
          "md5": "f832b527aa8aac14e5c9a70c578f75ec"
        }
      ]
    }
  ]
}
